function FSFile(a,b){this.fs=a;this.id=b}FSFile.prototype.getData=function(){void 0===this.data&&(this.data=this.fs.fs[this.id].data);return this.data};FSFile.prototype.setData=function(a){this.data=a};FSFile.prototype.close=function(){void 0!==this.data&&(this.fs.fs[this.id].data=this.data,this.fs._save())};function FSDir(a,b){this.fs=a;this.id=b}
FSDir.prototype.getFile=function(a){if("."==a)return this;if(".."==a)return new FSDir(this.fs,this.fs.fs[this.id].pid);var b=this.fs.findFile(a,this.id);return-1==b?"File `"+a+"' not found.":"d"==this.fs.fs[b].type?new FSDir(this.fs,b):"-"==this.fs.fs[b].type?new FSFile(this.fs,b):"There must be a bug!"};
FSDir.prototype.mkdir=function(a){if(-1!=this.fs.findFile(a,this.id))return"`"+a+"' already exists.";a=this.fs.fs.push({name:a,pid:this.id,type:"d",data:""})-1;this.fs._save();return new FSDir(this.fs,a)};FSDir.prototype.create=function(a){if(-1!=this.fs.findFile(a,this.id))return"`"+a+"' already exists.";a=this.fs.fs.push({name:a,pid:this.id,type:"-",data:""})-1;this.fs._save();return new FSFile(this.fs,a)};function FSLocalStorage(){this._load();this.cd("/")}
FSLocalStorage.prototype.cd=function(a){var b=this.getFileByPath(a);if(b instanceof FSDir)this.cwd=b;else return b.constructor===String?b:"`"+a+"' is not a directory."};FSLocalStorage.prototype.ls=function(){var a=this._listSubFiles(this.cwd.id),b="",c;for(c in a)b+=a[c].name,"d"==a[c].type&&(b+="/"),b+="\n";return b.slice(0,-1)};
FSLocalStorage.prototype.tree=function(a,b){var c=!1;if(!b||!a)b=0,a=this.cwd,c=!0;var d="",e=this._listSubFiles(a.id),f;for(f in e){for(var g=0;g<b;g++)d+="\t";d+=e[f].name;"d"==e[f].type?(d+="/\n",d+=this.tree(new FSDir(this,this.findFile(e[f].name,a.id)),b+1)):d+="\n"}c&&(d=d.slice(0,-1));return d};
FSLocalStorage.prototype.rm=function(a){var b=this.getFileByPath(a);if(0==b.id)delete this.fs,delete localStorage.local,this._load();else{if(b.constructor===String)return b;if(b instanceof FSDir)for(var c in this.fs)this.fs[c].pid==b.id&&this.rm(a+"/"+this.fs[c].name);for(this.fs[b.id]={removed:!0,pid:-1,name:"",data:""};this.fs[this.fs.length-1].removed;)this.fs.pop();this._save()}};
FSLocalStorage.prototype.open=function(a){var b=this.getFileByPath(a);return b instanceof FSDir?"`"+a+"' is a dierctory.":b};FSLocalStorage.prototype.mkdir=function(a){return this.cwd.mkdir(a)};FSLocalStorage.prototype.create=function(a){return this.cwd.create(a)};
FSLocalStorage.prototype.getFileByPath=function(a){if("/"==a)return new FSDir(this,0);if(""==a)return this.cwd;var a=a.split("/"),b=this.cwd;""==a[0]&&(b=new FSDir(this,0));for(var c in a)if(""!=a[c]){if(!(b instanceof FSDir))return"`"+a[c]+"' is not a directory.";b=b.getFile(a[c]);if(b.constructor===String)break}return b};FSLocalStorage.prototype.findFile=function(a,b){for(var c in this.fs)if(this.fs[c].pid==b&&this.fs[c].name==a)return c;return-1};
FSLocalStorage.prototype._listSubFiles=function(a){var b=[],c;for(c in this.fs)this.fs[c].pid==a&&0!=c&&b.push(this.fs[c]);return b};FSLocalStorage.prototype._load=function(){this.fs=localStorage.local?JSON.parse(atob(localStorage.local)):[{name:"",pid:0,type:"d",data:""}]};FSLocalStorage.prototype._save=function(){localStorage.local=""+this};FSLocalStorage.prototype.toString=function(){return btoa(JSON.stringify(this.fs))};
