function Vim(a,b){this.default_set={nu:!0,ts:4};this.mode="NORMAL";this.convas=a;this.tabs=[new VimWindow(this)];this.tab_current_wins=[this.tabs[0]];this.tab_id=0;this.win=this.tabs[0];this.fn_quit=b;this.quited=!1;this.render();var c=this.convas.getCursorPos();this.convas.setColor(FG_R|FG_G|FG_B);this.convas.cursorTo(26,6);this.convas.write("VIM.JS - Vi IMproved for JS");this.convas.cursorTo(34,8);this.convas.write("version 0.1");this.convas.cursorTo(30,9);this.convas.write("by eXerigumo Clanjor");
this.convas.cursorTo(17,10);this.convas.write("Vim.js is open source and freely distributable");this.convas.cursorTo(25,12);this.convas.write("Help poor children in Uganda!");this.convas.cursorTo(17,13);this.convas.write("type  :help iccf");this.convas.setColor(FG_B);this.convas.write("<Enter>");this.convas.setColor(FG_R|FG_G|FG_B);this.convas.write("       for information");this.convas.cursorTo(17,15);this.convas.write("type  :vimjs");this.convas.setColor(FG_B);this.convas.write("<Enter>");this.convas.setColor(FG_R|
FG_G|FG_B);this.convas.write("           to get the source code");this.convas.cursorTo(17,16);this.convas.write("type  :q");this.convas.setColor(FG_B);this.convas.write("<Enter>");this.convas.setColor(FG_R|FG_G|FG_B);this.convas.write("               to log out");this.convas.setCursorPos(c);this.is_cmd=!1;this.cmd=this.repeat="";var d=this;d.convas.readKey(!1,function e(a){var b=String.fromCharCode(a);console.log(a+"   "+b);d.processKey(b);d.quited||d.convas.readKey(!1,e)})}
Vim.prototype.render=function(){if(1<this.tabs.length){this.convas.cursorTo(0,0);this.convas.setColor(BG_H|BG_R|BG_G|BG_B);this.convas.write(formatTextRight("",this.convas.w-1));this.convas.setColor(BG_R|BG_G|BG_B);this.convas.write("X");this.convas.cursorTo(0,0);for(var a in this.tabs)a==this.tab_id?this.convas.setColor(FG_H|FG_R|FG_G|FG_B):this.convas.setColor(BG_R|BG_G|BG_B),this.convas.write(" "+this.tab_current_wins[a].buffer.name+" ");this._renderCurrentTab(0,1,this.convas.w,this.convas.h-1)}else this._renderCurrentTab(0,
0,this.convas.w,this.convas.h)};
Vim.prototype._renderCurrentTab=function(a,b,c,d){if(this.tabs[this.tab_id]===this.win){var f=new ConvasBuffer(c,d-1);this.win.render(f);this.convas.renderBuffer(f,a,b);this.convas.cursorTo(a,b+d-1);this.convas.setColor(FG_R|FG_G|FG_B);c=formatTextRight(this.win.status_line,c);this.convas.write(c);this.convas.cursorTo(f.x+a,f.y+b)}else this._doRender(this.tabs[this.tab_id],a,b,c,d-1),a=this.convas.getCursorPos(),this._blankCmdLine(),this.convas.setCursorPos(a);a=this.convas.getCursorPos();this.last_status_line&&
!this.err_msg&&(this.convas.cursorTo(0,this.convas.h-1),this.convas.setColor(FG_R|FG_G|FG_B),this.convas.write(this.last_status_line),delete this.last_status_line);this.err_msg&&(this.convas.cursorTo(0,this.convas.h-1),this.convas.setColor(FG_H|FG_R|FG_G|FG_B|BG_R),this.convas.write(this.err_msg),delete this.err_msg,delete this.last_status_line);"INSERT"==this.mode&&(this.convas.cursorTo(0,this.convas.h-1),this.convas.setColor(FG_H|FG_R|FG_G|FG_B),this.convas.write("-- "+this.mode+" --"));this.convas.setCursorPos(a);
"CMDLINE"==this.mode&&(this._blankCmdLine(),this.convas.write(":"+this.cmd))};
Vim.prototype._doRender=function(a,b,c,d,f){if(a instanceof VimWindow){if(1<f){var e=new ConvasBuffer(d,f);a.render(e);this.convas.renderBuffer(e,b,c);a===this.win&&this.convas.cursorTo(e.x+b,e.y+c)}f&&(e=new ConvasBuffer(d,1),e.color=BG_H|BG_R|BG_G|BG_B,a===this.win&&(e.color|=FG_H),a=formatTextTwoSides(a.buffer.name,a.status_line,d),e.write(a),this.convas.renderBuffer(e,b,c+f-1))}else if(!a.is_horizon){var e=f/a.wins.length,g;for(g in a.wins)this._doRender(a.wins[g],b,c+parseInt(g*e),d,g==a.wins.length-
1?f-parseInt(e*g):parseInt(e))}};
Vim.prototype.processKey=function(a){if("NORMAL"==this.mode){if(a==String.fromCharCode(27)){this.is_cmd=!1;this.repeat=this.cmd="";this.render();return}this.is_cmd?this.cmd+=a:/[1-9]/.test(a)?this.repeat+=a:""!=this.repeat&&/[0-9]/.test(a)?this.repeat+=a:(this.is_cmd=!0,this.repeat=parseInt(this.repeat),this.cmd+=a);for(var b in vim_cmds)if(a=vim_cmds[b].regex.exec(this.cmd)){this.is_cmd=!1;this.cmd=this.repeat="";vim_cmds[b].callback(this,a);break}}else if("CMDLINE"==this.mode)if("\r"==a){if(this.mode=
"NORMAL",this.cmd){this.execScript(this.cmd);if(this.quited)return;this.last_status_line=":"+this.cmd;this.cmd=""}}else"\b"==a?this.cmd?this.cmd=this.cmd.slice(0,-1):this.mode="NORMAL":this.cmd+=a;else"INSERT"==this.mode&&(a==String.fromCharCode(27)?(this.mode="NORMAL",this.win.moveCursor(-1,0)):this.win.input(a));this.render()};
Vim.prototype.closeTab=function(){1==this.tabs.length?this.quit():(this.tabs.splice(this.tab_id,1),this.tab_current_wins.splice(this.tab_id,1),this.tab_id>=this.tabs.length&&(this.tab_id=this.tabs.length-1),this.win=this.tab_current_wins[this.tab_id])};Vim.prototype.quit=function(){this.convas.clear();this.fn_quit();this.quited=!0};
Vim.prototype._blankCmdLine=function(){this.convas.cursorTo(0,this.convas.h-1);this.convas.setColor(FG_R|FG_G|FG_B);for(var a=0;a<this.convas.w;a++)this.convas.write(" ");this.convas.cursorTo(0,this.convas.h-1)};Vim.prototype._error=function(a,b){for(a=""+a;3>a.length;)a="0"+a;this.err_msg="E"+a+": "+b};
Vim.prototype.execScript=function(a){-1!=a.indexOf("\n")&&this._error(0,"TODO");var b;(b=/^((v)ne(w)?|new)$/.exec(a))?this.win.split("v"==b[2],!1):(b=/^(v)?sp(lit)?$/.exec(a))?this.win.split("v"==b[1],!0):/^q(uit)?$/.test(a)?this.win.close():(b=/^set\s+((no)?([a-z]+)(=(\d+))?)$/.exec(a))?b[2]&&b[4]?this._error(474,"Invalid argument: "+b[1]):(b[2]?b[5]=!1:b[5]||(b[5]=!0),void 0!==this.win.set[b[3]]?this.win.set[b[3]]=b[5]:void 0!==this.win.buffer.set[b[3]]?this.win.buffer.set[b[3]]=b[5]:this._error(474,
"Invalid argument: "+b[1])):"tabnew"==a?(a=new VimWindow(this),this.tabs.splice(this.tab_id+1,0,a),this.tab_current_wins.splice(this.tab_id+1,0,a),this.tab_id++,this.win=a):/^help\s+iccf$/.test(a)?(this.execScript("new"),this.execScript("set nonu"),this.win.buffer.setText("Vim is Charityware.  You can use and copy it as much as you like, but you are\nencouraged to make a donation for needy children in Uganda.  Please see visit\nthe ICCF web site, available at these URLs:\n\n\thttp://iccf-holland.org/\n\thttp://www.vim.org/iccf/\n\thttp://www.iccf.nl/\n\n"),
this.win.buffer.name="uganda.txt [Help]",this.win.buffer.set.ro=!0):"vimjs"==a?window.open("https://github.com/cjxgm/vimjs","_blank"):"debug"==a?this.win.buffer.lines.push("Hi!\x00"):this._error(492,"Not an editor command: "+a)};function VimWindow(a,b){this.vim=a;this.pa=b;this.line_start=0;this.buffer=new VimBuffer(a,"");this.x=this.y=0;this.set={};for(var c in this.vim.default_set)this.set[c]=this.vim.default_set[c]}
VimWindow.prototype.render=function(a){this.y<this.line_start?this.line_start=this.y:this.y-this.line_start>=a.h&&(this.line_start+=this.y-this.line_start-a.h+1);var b=0;this.set.nu&&(b=this.buffer.lines.length.toString().length+1,4>b&&(b=4));for(var c=0,d=0,f=0,e=this.line_start;e<this.buffer.lines.length&&f<a.h;e++){a.cursorTo(0,f);if(this.set.nu){lineno="";for(var g=b-1-(e+1).toString().length;0<g--;)lineno+=" ";lineno+=(e+1).toString();lineno+=" ";a.color=FG_H|FG_R|FG_G;a.write(lineno)}g=this.buffer.lines[e].split("");
a.color=FG_R|FG_G|FG_B;this.ix=0;e==this.y&&0==g.length&&(c=a.x,d=a.y);for(var h=0;h<g.length;h++)e==this.y&&(h==this.x?(c=a.x,d=a.y):"INSERT"==this.vim.mode&&g.length==this.x&&(c=a.x+1,d=a.y),h<this.x&&this.ix++),a.write(g[h]);f++}for(;f<a.h;f++)a.cursorTo(0,f),a.color=FG_H|FG_B,a.write("~");a.cursorTo(c,d);this.status_line=formatTextLeft(this.y+1+","+(this.x+1),14);this.status_line+=formatTextLeft("All",3)};
VimWindow.prototype.split=function(a,b){var c=new VimWindow(this.vim);b&&(c.buffer=this.buffer);if(this.pa)if(this.pa.is_horizon!=a){var d=new VimWindowSplit(this.vim,this.pa,a,c,this);this.pa=c.pa=d;var f=this.pa.wins.indexOf(this);this.pa.wins[f]=d}else c.pa=this.pa,f=this.pa.wins.indexOf(this),this.pa.wins.splice(f,0,c);else d=new VimWindowSplit(this.vim,this.pa,a,c,this),this.pa=c.pa=d,this.vim.tabs[this.vim.tab_id]=d;this.vim.win=c};
VimWindow.prototype.close=function(){this.pa?this.pa.killWindow(this):this.vim.closeTab()};VimWindow.prototype.moveCursor=function(a,b){this.x+=a;this.y+=b;this.y>=this.buffer.lines.length&&(this.y=this.buffer.lines.length-1);0>this.y&&(this.y=0);"INSERT"==this.vim.mode?this.x>this.buffer.lines[this.y].length&&(this.x=this.buffer.lines[this.y].length):this.x>=this.buffer.lines[this.y].length&&(this.x=this.buffer.lines[this.y].length-1);0>this.x&&(this.x=0)};
VimWindow.prototype.input=function(a){"\r"==a?(this.buffer.insertNewLine(this.x,this.y),this.x=0,this.moveCursor(0,1)):"\b"==a?0!=this.x?(this.moveCursor(-1,0),this.buffer.killChar(this.x,this.y)):(this.buffer.killLine(this.y),this.moveCursor(0,-1),this.goEOL()):(this.buffer.insertCharAt(this.x,this.y,a),this.moveCursor(1,0))};VimWindow.prototype.goBOL=function(a){this.x=0;a&&(a=/^[ \t]+/.exec(this.buffer.lines[this.y]))&&this.moveCursor(a[0].length,0)};
VimWindow.prototype.goEOL=function(){this.x=this.buffer.lines[this.y].length-1;this.moveCursor(1,0)};VimWindow.prototype.skipRegex=function(a){var b=this.buffer.lines[this.y].slice(this.x);(a=a.exec(b))?a[0]=a[0].length:a=[0];this.x+=a[0];this.x>=this.buffer.lines[this.y].length&&(this.y==this.buffer.lines.length-1?this.moveCursor(-1,0):(this.x=0,this.moveCursor(0,1)))};VimWindow.prototype.goWord=function(){this.skipRegex(/^(([a-zA-Z0-9_]+|[^a-zA-Z0-9_. ]+|\.)? *)/)};VimWindow.prototype.goToken=function(){this.skipRegex(/^([^ ]* *)/)};
VimWindow.prototype.newLineAfter=function(){this.buffer.newLine(this.y+1);this.moveCursor(0,1)};VimWindow.prototype.newLineBefore=function(){this.buffer.newLine(this.y);this.moveCursor(0,0)};VimWindow.prototype.killChar=function(){this.buffer.killChar(this.x,this.y);this.moveCursor(0,0)};function VimWindowSplit(a,b,c,d,f){this.vim=a;this.pa=b;this.wins=[d,f];this.is_horizon=c}
VimWindowSplit.prototype.killWindow=function(a){a=this.wins.indexOf(a);this.wins.splice(a,1);a>=this.wins.length&&(a=this.wins.length-1);this.vim.win=this.wins[a];1==this.wins.length&&(this.pa?this.pa.wins[this.pa.wins.indexOf(this)]=this.vim.win:this.vim.tabs[this.vim.tab_id]=this.vim.win,this.vim.win.pa=void 0);this.vim.tab_current_wins[this.vim.tab_id]=this.vim.win};function VimBuffer(a,b,c){this.vim=a;this.setText(b);this.name=c?c:"[No Name]";this.set={ro:!1,modified:!1}}
VimBuffer.prototype.setText=function(a){this.lines=a.split("\n");this.lines.length||(this.lines[0]="")};VimBuffer.prototype.insertCharAt=function(a,b,c){var d=this.lines[b];this.lines[b]=d.slice(0,a)+c+d.slice(a)};VimBuffer.prototype.newLine=function(a){this.lines.splice(a,0,"")};VimBuffer.prototype.insertNewLine=function(a,b){var c=this.lines[b].slice(a);this.lines[b]=this.lines[b].slice(0,a);this.lines.splice(b+1,0,c)};
VimBuffer.prototype.killChar=function(a,b){var c=this.lines[b];this.lines[b]=c.slice(0,a)+c.slice(a+1)};VimBuffer.prototype.killLine=function(a){this.lines.splice(a,1);0==this.lines.length&&(this.lines[0]="")};
